spring.application.name=SFPN

server.port = 8008
server.servlet.session.persistent=false

spring.thymeleaf.cache=false

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#211.238.142.131:1521:xe
spring.datasource.username=c##sistuser
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wogn2918@gmail.com
spring.mail.password=kgxxwikuufvawcdo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.rquired=true
spring.mail.properties.mail.smtp.connctiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.auth-code-expiration-millis=1800000


spring.security.oauth2.client.registration.google.client-id=517426993358-dt4a14ojtq7ghlrc8mev6bjr0v60h672.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email, profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8008/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code

spring.security.oauth2.client.registration.kakao.client-authentication-method=POST
spring.security.oauth2.client.registration.kakao.client-id=60c1dc31be129678e6dc0c3fcb4c1c1c
spring.security.oauth2.client.registration.kakao.client-secret=0woO8VnFJKLKJk9bjf0qltX9uBXk35Bq
spring.security.oauth2.client.registration.kakao.scope=profile_nickname, account_email
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8008/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code

spring.security.oauth2.client.registration.naver.client-name=Naver
spring.security.oauth2.client.registration.naver.client-id=yDgHSQAXAH3cg0V13_mp
spring.security.oauth2.client.registration.naver.client-secret=fXb04gpxtK
spring.security.oauth2.client.registration.naver.scope=name, email
spring.security.oauth2.client.registration.naver.redirect-uri=http://localhost:8008/login/oauth2/code/naver
spring.security.oauth2.client.registration.naver.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

spring.security.oauth2.client.provider.naver.authorization-uri=https://nid.naver.com/oauth2.0/authorize
spring.security.oauth2.client.provider.naver.token-uri=https://nid.naver.com/oauth2.0/token
spring.security.oauth2.client.provider.naver.user-info-uri=https://openapi.naver.com/v1/nid/me
spring.security.oauth2.client.provider.naver.user-name-attribute=response

ffmpeg.main.location=c:/project/ffmpeg/bin/ffmpeg.exe
ffmpeg.probe.location==c:/project/ffmpeg/bin/ffprobe.exe
spring.servlet.multipart.max-file-size=314572800
spring.servlet.multipart.max-request-size=1004857600

online.video.file.dir=C:/project/sts4/SFPN/src/main/resources/static/video/
